# Generated by Django 4.1.4 on 2023-01-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='code',
        ),
    ]
