# Generated by Django 4.1.4 on 2023-01-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_disease_plant_delete_landmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='disease_code',
            new_name='disease',
        ),
    ]
