# Generated by Django 4.1.4 on 2023-01-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_status'),
        ('plants', '0003_remove_dignoisis_type_dignoisis_result_picture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dignoisis',
            new_name='Diagnoisis',
        ),
    ]
