# Generated by Django 4.1.4 on 2023-01-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_status'),
        ('plants', '0004_rename_dignoisis_diagnoisis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnoisis',
            new_name='Diagnosis',
        ),
    ]
