# Generated by Django 4.1.4 on 2023-01-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_rename_diagnoisis_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='type',
            new_name='plant_type',
        ),
    ]
