# Generated by Django 4.1.4 on 2023-01-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_rename_type_plant_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disease_id', to='plants.disease'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_id', to='plants.plant'),
        ),
    ]
