# Generated by Django 4.1.4 on 2023-01-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_diagnosis_disease_alter_diagnosis_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.disease'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.plant'),
        ),
    ]
