# Generated by Django 4.1.4 on 2023-01-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(default='OK', max_length=10, verbose_name='사용자 상태'),
        ),
    ]
