# Generated by Django 4.1.4 on 2023-01-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default=2, max_length=100, verbose_name='사용자 비밀번호'),
            preserve_default=False,
        ),
    ]
