# Generated by Django 4.1.4 on 2023-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_remove_member_created_at_remove_member_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
